### ISSUE TITLE
Live stream stopped working

### ISSUE THREAD

**Issue by petroid** [Twilight0/plugin.video.euronews.com#15]
Hello!
Kodi 18.9, OSMC, Raspberry Pi 3B.
A week or so ago live stream stopped working. Probably remote site issues but also, if you pushed updates, they may have broken something. I have your repo as well as you libs repo added and autoupdate enabled.
This is what I get in log:
```
2021-02-27 12:13:30.278 T:1916134320   DEBUG: ------ Window Init (DialogBusy.xml) ------
2021-02-27 12:13:30.335 T:1743773920   DEBUG: -->Python Interpreter Initialized<--
2021-02-27 12:13:30.335 T:1743773920   DEBUG: CPythonInvoker(26, /home/osmc/.kodi/addons/plugin.video.euronews.com/addon.py): the source file to load is "/home/osmc/.kodi/addons/plugin.video.euronews.com/addon.py"
2021-02-27 12:13:30.336 T:1743773920   DEBUG: CPythonInvoker(26, /home/osmc/.kodi/addons/plugin.video.euronews.com/addon.py): setting the Python path to /home/osmc/.kodi/addons/plugin.video.euronews.com:/home/osmc/.kodi/addons/script.module.kodi-six/libs:/home/osmc/.kodi/addons/script.module.tulip/lib:/usr/lib/python2.7:/usr/lib/python2.7/plat-arm-linux-gnueabihf:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/gtk-2.0
2021-02-27 12:13:30.336 T:1743773920   DEBUG: CPythonInvoker(26, /home/osmc/.kodi/addons/plugin.video.euronews.com/addon.py): entering source directory /home/osmc/.kodi/addons/plugin.video.euronews.com
2021-02-27 12:13:30.336 T:1743773920   DEBUG: CPythonInvoker(26, /home/osmc/.kodi/addons/plugin.video.euronews.com/addon.py): instantiating addon using automatically obtained id of "plugin.video.euronews.com" dependent on version 0.0.0 of the xbmc.python api
2021-02-27 12:13:30.543 T:1518846176   DEBUG: CWebServer[80]: request received for /jsonrpc
2021-02-27 12:13:31.310 T:1743773920   DEBUG: CAddonSettings[plugin.video.euronews.com]: loading setting definitions
2021-02-27 12:13:31.310 T:1743773920   DEBUG: CAddonSettings[plugin.video.euronews.com]: trying to load setting definitions from old format...
2021-02-27 12:13:31.311 T:1743773920   DEBUG: CAddonSettings[plugin.video.euronews.com]: loading setting values
2021-02-27 12:13:31.544 T:1518846176   DEBUG: CWebServer[80]: request received for /jsonrpc
2021-02-27 12:13:31.817 T:1743773920   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'startswith'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.euronews.com/addon.py", line 31, in <module>
                                                euronews.indexer().live()
                                              File "/home/osmc/.kodi/addons/plugin.video.euronews.com/resources/lib/euronews.py", line 156, in live
                                                stream = self.resolve_live(lang=lang)
                                              File "/home/osmc/.kodi/addons/plugin.video.euronews.com/resources/lib/euronews.py", line 349, in resolve_live
                                                if result.startswith('//'):
                                            AttributeError: 'NoneType' object has no attribute 'startswith'
                                            -->End of Python script error report<--
2021-02-27 12:13:31.817 T:1743773920   DEBUG: onExecutionDone(26, /home/osmc/.kodi/addons/plugin.video.euronews.com/addon.py)
2021-02-27 12:13:31.850 T:1916134320   DEBUG: ------ Window Init (DialogNotification.xml) ------
2021-02-27 12:13:31.964 T:1743773920    INFO: Python interpreter stopped
2021-02-27 12:13:31.964 T:1743773920   DEBUG: Thread LanguageInvoker 1743773920 terminating
2021-02-27 12:13:31.966 T:1586028768   DEBUG: Thread scriptobs 1586028768 terminating
2021-02-27 12:13:31.967 T:1916134320   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2021-02-27 12:13:31.967 T:1916134320   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.euronews.com/?action=live&title=%D0%9F%D1%80%D1%8F%D0%BC%D0%B0%D1%8F+%D1%82%D1%80%D0%B0%D0%BD%D1%81%D0%BB%D1%8F%D1%86%D0%B8%D1%8F]
2021-02-27 12:13:31.967 T:1916134320   DEBUG: Playlist Player: one or more items failed to play... aborting playback

```

**Comment by Twilight0** [comment]
The whole addon appears to be broken, no time or will to update it, I will probably archive it and remove it from release repository, sorry for any inconveniences caused.
